import type { Metadata, Viewport } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { Suspense } from 'react'
import './globals.css'

// Build-time env gate: importing these runs their Zod parse, failing the build on a missing/bad var.
import '@/lib/env'
import '@/lib/env.server'
import { ActionToast } from '@/components/action-toast'
import { ToastProvider } from '@/components/toast-provider'
import { DARK_SURFACE } from '@/components/logo/logo-colors'
import { APPLE_SPLASH_SCREENS } from './apple-splash'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'eggplant_notes',
  description: 'AI powered notes with spaced-repetition recall cards.',
  // Tells iOS Safari to launch "Add to Home Screen" standalone (no browser chrome) and emits the
  // apple-mobile-web-app-* meta. The manifest covers this for Android/Chrome; iOS needs it here.
  // startupImage: per-device launch screens (apple-touch-startup-image). iOS ignores the manifest's
  // background_color, so without these it paints a WHITE launch/relaunch screen before the app renders
  // — the PWA-only white flash. Solid brand-dark PNGs, generated by scripts/gen-apple-splash.mjs.
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Eggplant',
    startupImage: [...APPLE_SPLASH_SCREENS],
  },
}

export const viewport: Viewport = {
  themeColor: DARK_SURFACE,
  // Shrink the LAYOUT viewport when the soft keyboard opens (instead of the default overlay). Keeps
  // `position: fixed` bottom-anchored UI — the mobile combobox/multi-select Sheet — above the keyboard
  // so its search input stays visible; also stops focused inputs anywhere from being hidden behind it.
  interactiveWidget: 'resizes-content',
  // Emits <meta name="color-scheme" content="dark"> so the browser paints its WINDOW canvas dark for the
  // navigation-commit frame — the one painted before the document's own styles (CSS, inline <html> bg,
  // the veil) resolve. Without it that first frame is the UA default white: the intro flash.
  colorScheme: 'dark',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      // Inline so the browser paints brand-dark from the FIRST frame, before globals.css loads. The
      // `.dark { color-scheme; --background }` rules are render-blocking but still resolve a beat after
      // the HTML — in that gap the UA paints its default WHITE canvas (the intro flash). Setting both
      // here, in the initial markup, removes that pre-stylesheet white frame and inter-page blanks.
      style={{ colorScheme: 'dark', backgroundColor: DARK_SURFACE }}
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        {children}
        <Suspense fallback={null}>
          <ActionToast />
        </Suspense>
        <ToastProvider />
      </body>
    </html>
  )
}
